[2021-10-14 19:26:33,790] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2021-10-14T19:08:59.171717+00:00 [queued]>
[2021-10-14 19:26:33,803] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2021-10-14T19:08:59.171717+00:00 [queued]>
[2021-10-14 19:26:33,803] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 19:26:33,803] {taskinstance.py:1242} INFO - Starting attempt 2 of 2
[2021-10-14 19:26:33,803] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-14 19:26:33,812] {taskinstance.py:1262} INFO - Executing <Task(HttpSensor): is_api_available> on 2021-10-14 19:08:59.171717+00:00
[2021-10-14 19:26:33,817] {standard_task_runner.py:52} INFO - Started process 129 to run task
[2021-10-14 19:26:33,819] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2021-10-14T19:08:59.171717+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmptjtzbv21', '--error-file', '/tmp/tmpwzlu55dc']
[2021-10-14 19:26:33,819] {standard_task_runner.py:77} INFO - Job 42: Subtask is_api_available
[2021-10-14 19:26:33,850] {logging_mixin.py:109} INFO - Running <TaskInstance: user_processing.is_api_available manual__2021-10-14T19:08:59.171717+00:00 [running]> on host 981af2cc3d86
[2021-10-14 19:26:33,884] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2021-10-14T19:08:59.171717+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-14T19:08:59.171717+00:00
[2021-10-14 19:26:33,884] {http.py:101} INFO - Poking: api/
[2021-10-14 19:26:33,892] {base.py:79} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: {}
[2021-10-14 19:26:33,894] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2021-10-14 19:26:34,128] {base.py:249} INFO - Success criteria met. Exiting.
[2021-10-14 19:26:34,140] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20211014T190859, start_date=20211014T192633, end_date=20211014T192634
[2021-10-14 19:26:34,192] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-14 19:26:34,233] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
