[2021-10-13 22:52:39,321] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user manual__2021-10-13T22:50:14.704120+00:00 [queued]>
[2021-10-13 22:52:39,331] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: user_processing.processing_user manual__2021-10-13T22:50:14.704120+00:00 [queued]>
[2021-10-13 22:52:39,332] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 22:52:39,332] {taskinstance.py:1242} INFO - Starting attempt 2 of 2
[2021-10-13 22:52:39,332] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-10-13 22:52:39,346] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): processing_user> on 2021-10-13 22:50:14.704120+00:00
[2021-10-13 22:52:39,350] {standard_task_runner.py:52} INFO - Started process 2077 to run task
[2021-10-13 22:52:39,353] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'processing_user', 'manual__2021-10-13T22:50:14.704120+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpbno1m5dj', '--error-file', '/tmp/tmp27nb_jxm']
[2021-10-13 22:52:39,353] {standard_task_runner.py:77} INFO - Job 27: Subtask processing_user
[2021-10-13 22:52:39,383] {logging_mixin.py:109} INFO - Running <TaskInstance: user_processing.processing_user manual__2021-10-13T22:50:14.704120+00:00 [running]> on host 981af2cc3d86
[2021-10-13 22:52:39,451] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=processing_user
AIRFLOW_CTX_EXECUTION_DATE=2021-10-13T22:50:14.704120+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-10-13T22:50:14.704120+00:00
[2021-10-13 22:52:39,464] {python.py:152} INFO - Done. Returned value was: None
[2021-10-13 22:52:39,476] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=processing_user, execution_date=20211013T225014, start_date=20211013T225239, end_date=20211013T225239
[2021-10-13 22:52:39,491] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-10-13 22:52:39,520] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-10-13 23:34:12,248] {taskinstance.py:1029} INFO - Dependencies not met for <TaskInstance: user_processing.processing_user scheduled__2021-10-12T00:00:00+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state which is not a valid state for execution. The task must be cleared in order to be run.
[2021-10-13 23:34:12,249] {local_task_job.py:99} INFO - Task is not able to be run
[2021-10-13 23:35:14,214] {taskinstance.py:1029} INFO - Dependencies not met for <TaskInstance: user_processing.processing_user scheduled__2021-10-12T00:00:00+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state which is not a valid state for execution. The task must be cleared in order to be run.
[2021-10-13 23:35:14,215] {local_task_job.py:99} INFO - Task is not able to be run
